name: fixonnextupdate
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'allowlist'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Thanks for your support, domain(s) has been added to the allowlist and will be removed in the next update. The update takes place every 12 hours. Updated list versions are usually available at 16:00 UTC and 04:00 UTC.
